version: '3'

services:
  postgres:
    image: postgres:9-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - pg
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8880:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    networks:
      - pg
    depends_on:
      - postgres
networks:
  pg:
    driver: bridge